name: chat_app
description: A chat application using Flutter and Firebase
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  firebase_database: ^11.1.4
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.4
  timeago: ^3.6.0
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  permission_handler: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
